import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { FlatList, Platform, StyleSheet, Switch, Text, TouchableOpacity, View } from "react-native";
import { AppScreen, Card, Chevron, PageHeader, palette, PrimaryButton, SectionTitle, StatusPill } from "@/components/beepai-ui";
import { useBeepAI } from "@/lib/beepai-context";
import type { WorkflowStep } from "@/lib/beepai-data";

export default function AutomationDetailScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { automations, runningIds, runAutomation, toggleAutomation } = useBeepAI(); const automation = automations.find((item) => item.id === id);
  if (!automation) return <AppScreen><PageHeader title="Automation" back /><View style={styles.missing}><Text style={styles.missingTitle}>Automation unavailable</Text><Text style={styles.missingText}>This automation could not be found on this device.</Text></View></AppScreen>;
  const active = automation.status === "active";
  const allowedCount = automation.permissions.filter((item) => item.state === "allowed").length;
  return <AppScreen><FlatList data={automation.steps.slice(0, 3)} keyExtractor={(item) => item.id} renderItem={({ item, index }) => <StepPreview item={item} last={index === 2} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<>
    <PageHeader title="Automation" back right={<StatusPill label={active ? "Active" : "Paused"} tone={active ? "green" : "orange"} />} />
    <Card style={styles.heroCard}><View style={styles.heroTop}><View style={styles.heroGlyph}><MaterialIcons name={automation.category === "Files" ? "folder" : automation.category === "Messages" ? "chat" : "description"} size={24} color={palette.primary} /></View><View style={styles.heroCopy}><Text style={styles.heroName}>{automation.name}</Text><Text style={styles.heroDescription}>{automation.description}</Text></View></View><View style={styles.heroDivider} /><View style={styles.activateRow}><View><Text style={styles.activateTitle}>Automation is {active ? "active" : "paused"}</Text><Text style={styles.activateText}>{active ? automation.nextRun : "It will not run until you activate it."}</Text></View><Switch value={active} onValueChange={() => toggleAutomation(automation.id)} trackColor={{ false: "#D0D5DD", true: "#BFA9FA" }} thumbColor={active ? palette.primary : "#FFFFFF"} /></View></Card>
    <PrimaryButton label={runningIds.includes(automation.id) ? "Running privately" : "Run now"} icon={runningIds.includes(automation.id) ? "sync" : "play-arrow"} loading={runningIds.includes(automation.id)} onPress={() => runAutomation(automation.id)} style={styles.runButton} />
    {automation.lastReport !== undefined && <ReportCard report={automation.lastReport} />}
    <View style={styles.metrics}><MiniMetric value={`${automation.totalRuns}`} label="Total runs" icon="query-stats" /><MiniMetric value={`${automation.successRate}%`} label="Success rate" icon="check-circle" /><MiniMetric value={automation.duration} label="Last duration" icon="timer" /></View>
    <SectionTitle eyebrow="HOW IT WORKS" title="Workflow preview" action={<TouchableOpacity onPress={() => router.push({ pathname: "/workflow/[id]", params: { id: automation.id } })}><Text style={styles.sectionAction}>View all</Text></TouchableOpacity>} />
  </>} ListFooterComponent={<><SectionTitle eyebrow="CONTROL" title="Automation settings" /><TouchableOpacity onPress={() => router.push({ pathname: "/permissions/[id]", params: { id: automation.id } })} activeOpacity={0.76}><Card style={styles.controlRow}><View style={styles.controlIcon}><MaterialIcons name="admin-panel-settings" size={21} color={palette.primary} /></View><View style={styles.controlCopy}><Text style={styles.controlTitle}>Permissions</Text><Text style={styles.controlText}>{allowedCount} of {automation.permissions.length} permissions allowed</Text></View><Chevron /></Card></TouchableOpacity><Card style={styles.privateCard}><MaterialIcons name="lock" size={19} color={palette.mint} /><View style={styles.privateCopy}><Text style={styles.privateTitle}>Your working file and results stay on this device</Text><Text style={styles.privateText}>{Platform.OS === "web" ? "Browser preview only: the encryption key lasts for this page session; a reload requires redeeming again while the package is available. " : "The JavaScript package is encrypted with a key held in this device’s secure storage. "}Its private cloud copy expires seven days after first redemption. It runs in an isolated JavaScript sandbox with network access disabled; no separate interpreter is downloaded. Your working file and report stay on this device.</Text></View></Card></>} /></AppScreen>;
}
function StepPreview({ item, last }: { item: WorkflowStep; last: boolean }) { return <View style={styles.stepLine}><View style={styles.stepTrack}><View style={[styles.stepIcon, { backgroundColor: item.kind === "process" ? "#EAF1FF" : palette.primaryLight }]}><MaterialIcons name={item.icon} size={18} color={item.kind === "process" ? palette.blue : palette.primary} /></View>{!last && <View style={styles.line} />}</View><View style={styles.stepCopy}><Text style={styles.stepTitle}>{item.label}</Text><Text style={styles.stepText}>{item.detail}</Text></View></View>; }
function MiniMetric({ value, label, icon }: { value: string; label: string; icon: keyof typeof MaterialIcons.glyphMap }) { return <View style={styles.metric}><MaterialIcons name={icon} size={16} color={palette.primary} /><Text numberOfLines={1} style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function ReportCard({ report }: { report: unknown }) {
  const record = typeof report === "object" && report !== null && !Array.isArray(report) ? report as Record<string, unknown> : { result: report };
  return <Card style={styles.reportCard}><View style={styles.reportHeading}><View style={styles.reportIcon}><MaterialIcons name="insert-chart-outlined" size={19} color={palette.primary} /></View><View><Text style={styles.reportEyebrow}>LOCAL RESULT</Text><Text style={styles.reportTitle}>{typeof record.title === "string" ? record.title : "Automation report"}</Text></View></View><View style={styles.reportRows}>{Object.entries(record).filter(([key]) => key !== "title").map(([key, value]) => <View key={key} style={styles.reportRow}><Text style={styles.reportLabel}>{key.replace(/_/g, " ")}</Text><Text selectable style={styles.reportValue}>{typeof value === "string" ? value : typeof value === "number" ? value.toLocaleString() : JSON.stringify(value, null, 2)}</Text></View>)}</View><View style={styles.reportPrivacy}><MaterialIcons name="lock" size={14} color={palette.mint} /><Text style={styles.reportPrivacyText}>Generated on this device. Your working file was not uploaded.</Text></View></Card>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingTop: 9, paddingBottom: 27 }, missing: { margin: 20, padding: 22, backgroundColor: "#FFFFFF", borderRadius: 19, alignItems: "center" }, missingTitle: { fontSize: 17, fontWeight: "900", color: palette.ink }, missingText: { fontSize: 13, color: palette.muted, marginTop: 7, textAlign: "center" }, heroCard: { padding: 15, marginTop: 6, marginBottom: 14 }, heroTop: { flexDirection: "row", gap: 11 }, heroGlyph: { width: 47, height: 47, borderRadius: 15, backgroundColor: palette.primaryLight, justifyContent: "center", alignItems: "center" }, heroCopy: { flex: 1 }, heroName: { color: palette.ink, fontSize: 18, fontWeight: "900", letterSpacing: -0.4 }, heroDescription: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 4 }, heroDivider: { height: 1, backgroundColor: "#EEF0F5", marginVertical: 14 }, activateRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 }, activateTitle: { color: palette.ink, fontSize: 13, fontWeight: "900" }, activateText: { color: palette.muted, fontSize: 11, marginTop: 3 }, runButton: { marginBottom: 14 }, metrics: { flexDirection: "row", gap: 9, marginBottom: 27 }, metric: { flex: 1, backgroundColor: "#FFFFFF", borderRadius: 15, borderWidth: 1, borderColor: palette.line, padding: 10 }, metricValue: { color: palette.ink, fontSize: 14, fontWeight: "900", marginTop: 7 }, metricLabel: { color: palette.muted, fontSize: 10, fontWeight: "700", marginTop: 2 }, sectionAction: { color: palette.primary, fontSize: 13, fontWeight: "800", padding: 4 }, stepLine: { flexDirection: "row", minHeight: 71 }, stepTrack: { alignItems: "center", width: 43 }, stepIcon: { width: 35, height: 35, borderRadius: 12, alignItems: "center", justifyContent: "center", zIndex: 1 }, line: { position: "absolute", top: 33, bottom: -2, width: 2, backgroundColor: "#DED6F8" }, stepCopy: { flex: 1, paddingTop: 5, paddingBottom: 12 }, stepTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, stepText: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, controlRow: { padding: 12, flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 11 }, controlIcon: { width: 39, height: 39, borderRadius: 12, backgroundColor: palette.primaryLight, alignItems: "center", justifyContent: "center" }, controlCopy: { flex: 1 }, controlTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, controlText: { color: palette.muted, fontSize: 11, marginTop: 3 }, privateCard: { padding: 13, flexDirection: "row", gap: 10, marginTop: 16, borderColor: "#DFF2E3", backgroundColor: "#FAFFFB" }, privateCopy: { flex: 1 }, privateTitle: { color: palette.ink, fontSize: 13, fontWeight: "900" }, privateText: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 },
 reportCard: { padding: 14, marginBottom: 20, borderColor: "#D9EDE0", backgroundColor: "#FCFFFD" }, reportHeading: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 9 }, reportIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: "#EEF8F1", alignItems: "center", justifyContent: "center" }, reportEyebrow: { color: palette.mint, fontSize: 8, fontWeight: "900", letterSpacing: 0.9 }, reportTitle: { color: palette.ink, fontSize: 14, fontWeight: "900", marginTop: 2 }, reportRows: { borderTopWidth: 1, borderTopColor: "#E5EFE8" }, reportRow: { paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: "#EAF1EC" }, reportLabel: { color: palette.muted, fontSize: 10, fontWeight: "800", textTransform: "capitalize" }, reportValue: { color: palette.ink, fontSize: 13, lineHeight: 19, fontWeight: "800", marginTop: 3 }, reportPrivacy: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 10 }, reportPrivacyText: { color: palette.muted, fontSize: 9 },
});
