import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppScreen, Card, PageHeader, palette, StatusPill } from "@/components/beepai-ui";
import { getPlan, useBeepAI } from "@/lib/beepai-context";
import { plans, type SubscriptionPlan } from "@/lib/beepai-data";

export default function PlansScreen() { const router = useRouter(); const { currentPlanId, selectPlan } = useBeepAI(); const currentPlan = getPlan(currentPlanId); return <AppScreen><FlatList data={plans} keyExtractor={(item) => item.id} renderItem={({ item }) => <PlanCard plan={item} current={item.id === currentPlanId} onSelect={() => selectPlan(item.id)} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<><PageHeader title="Plans & billing" subtitle="Choose the capacity that fits your work." back /><Card style={styles.current}><View style={[styles.currentGlyph, { backgroundColor: `${currentPlan.accent}17` }]}><MaterialIcons name="workspace-premium" size={20} color={currentPlan.accent} /></View><View style={styles.currentCopy}><Text style={styles.currentLabel}>CURRENT PLAN</Text><Text style={styles.currentTitle}>{currentPlan.name} · {currentPlan.price} / month</Text></View></Card><Text style={styles.heading}>Monthly plans</Text></>} ListFooterComponent={<Card style={styles.billingNote}><MaterialIcons name="shield" size={20} color={palette.mint} /><View style={styles.billingCopy}><Text style={styles.billingTitle}>Your plan is flexible</Text><Text style={styles.billingText}>Prices and plan details are managed by BeepAI. You will always see changes before they take effect.</Text></View></Card>} /> </AppScreen>; }
function PlanCard({ plan, current, onSelect }: { plan: SubscriptionPlan; current: boolean; onSelect: () => void }) { return <Card style={[styles.planCard, current && { borderColor: plan.accent, borderWidth: 1.5 }]}><View style={styles.planHeader}><View style={[styles.planGlyph, { backgroundColor: `${plan.accent}15` }]}><MaterialIcons name={plan.id === "business" ? "apartment" : plan.id === "professional" ? "business-center" : plan.id === "personal" ? "person" : "eco"} size={22} color={plan.accent} /></View><View style={styles.planCopy}><View style={styles.planNameLine}><Text style={[styles.planName, { color: plan.accent }]}>{plan.name}</Text>{current && <StatusPill label="Current" tone="violet" />}</View><Text style={styles.planSummary}>{plan.summary}</Text></View></View><View style={styles.priceRow}><Text style={styles.price}>{plan.price}</Text><Text style={styles.month}> / month</Text></View><View style={styles.featureList}>{plan.features.map((feature) => <View style={styles.feature} key={feature}><MaterialIcons name="check-circle" size={16} color={plan.accent} /><Text style={styles.featureText}>{feature}</Text></View>)}</View><TouchableOpacity onPress={onSelect} activeOpacity={0.84} style={[styles.planButton, { backgroundColor: current ? "#F2F4F7" : plan.accent }]}><Text style={[styles.planButtonText, { color: current ? palette.muted : "#FFFFFF" }]}>{current ? "Current plan" : `Choose ${plan.name}`}</Text></TouchableOpacity></Card>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingTop: 9, paddingBottom: 27 }, current: { padding: 13, flexDirection: "row", gap: 10, marginTop: 5, marginBottom: 25 }, currentGlyph: { width: 38, height: 38, borderRadius: 12, justifyContent: "center", alignItems: "center" }, currentCopy: { flex: 1 }, currentLabel: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, currentTitle: { color: palette.ink, fontSize: 13, fontWeight: "900", marginTop: 4 }, heading: { color: palette.ink, fontSize: 18, fontWeight: "900", marginBottom: 10 }, planCard: { padding: 15, marginBottom: 12 }, planHeader: { flexDirection: "row", gap: 10 }, planGlyph: { height: 41, width: 41, borderRadius: 13, alignItems: "center", justifyContent: "center" }, planCopy: { flex: 1 }, planNameLine: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 7 }, planName: { fontSize: 16, fontWeight: "900" }, planSummary: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, priceRow: { flexDirection: "row", alignItems: "baseline", marginTop: 16 }, price: { fontSize: 25, color: palette.ink, fontWeight: "900", letterSpacing: -0.8 }, month: { color: palette.muted, fontSize: 12, fontWeight: "700" }, featureList: { gap: 7, marginTop: 13, marginBottom: 15 }, feature: { flexDirection: "row", alignItems: "center", gap: 7 }, featureText: { color: "#465167", fontSize: 12, fontWeight: "600" }, planButton: { minHeight: 43, borderRadius: 13, alignItems: "center", justifyContent: "center" }, planButtonText: { fontSize: 13, fontWeight: "900" }, billingNote: { padding: 13, marginTop: 6, backgroundColor: "#FAFFFB", borderColor: "#DFF2E3", flexDirection: "row", gap: 10 }, billingCopy: { flex: 1 }, billingTitle: { color: palette.ink, fontSize: 13, fontWeight: "900" }, billingText: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 4 },
});
