import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppScreen, BrandMark, Card, palette, StatusPill } from "@/components/beepai-ui";
import { useBeepAI } from "@/lib/beepai-context";
import type { RunRecord } from "@/lib/beepai-data";

export default function ActivityScreen() {
  const router = useRouter();
  const { runs } = useBeepAI();
  const [filter, setFilter] = useState<"all" | "success" | "failed">("all");
  const filteredRuns = useMemo(() => filter === "all" ? runs : runs.filter((item) => item.status === filter), [runs, filter]);
  return <AppScreen><FlatList data={filteredRuns} keyExtractor={(item) => item.id} renderItem={({ item }) => <RunRow item={item} onPress={() => router.push({ pathname: "/run/[id]", params: { id: item.id } })} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<>
    <View style={styles.topRow}><BrandMark /><View style={styles.localChip}><MaterialIcons name="lock" size={14} color={palette.mint} /><Text style={styles.localText}>Local history</Text></View></View>
    <Text style={styles.title}>Activity</Text><Text style={styles.subtitle}>A private record of every automation run.</Text>
    <Card style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="auto-graph" size={20} color={palette.violet} /></View><View style={styles.summaryText}><Text style={styles.summaryTitle}>This month</Text><Text style={styles.summaryDetail}>{runs.filter((item) => item.status === "success").length} completed runs · {runs.filter((item) => item.status === "failed").length} needs attention</Text></View></Card>
    <View style={styles.filters}><ActivityFilter label="All runs" active={filter === "all"} onPress={() => setFilter("all")} /><ActivityFilter label="Success" active={filter === "success"} onPress={() => setFilter("success")} /><ActivityFilter label="Needs review" active={filter === "failed"} onPress={() => setFilter("failed")} /></View>
    <Text style={styles.listTitle}>{filter === "all" ? "All activity" : filter === "success" ? "Successful runs" : "Runs needing review"}</Text>
  </>} ListEmptyComponent={<Card style={styles.empty}><MaterialIcons name="history" size={26} color={palette.violet} /><Text style={styles.emptyText}>There are no runs in this view yet.</Text></Card>} /></AppScreen>;
}

function ActivityFilter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[styles.filter, active && styles.filterActive]}><Text style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></TouchableOpacity>; }
function RunRow({ item, onPress }: { item: RunRecord; onPress: () => void }) { const failed = item.status === "failed"; return <TouchableOpacity onPress={onPress} activeOpacity={0.76}><Card style={styles.row}><View style={[styles.rowIcon, { backgroundColor: failed ? "#FEECEC" : "#EAF9EE" }]}><MaterialIcons name={failed ? "error-outline" : "check"} color={failed ? palette.danger : palette.mint} size={19} /></View><View style={styles.rowCopy}><View style={styles.rowTitleLine}><Text numberOfLines={1} style={styles.rowTitle}>{item.automationName}</Text><StatusPill label={failed ? "Review" : "Success"} tone={failed ? "red" : "green"} /></View><Text numberOfLines={1} style={styles.rowDetail}>{item.summary}</Text><View style={styles.rowMeta}><Text>{item.timestamp}</Text><View style={styles.dot} /><Text>{item.duration}</Text></View></View><MaterialIcons name="chevron-right" color="#98A2B3" size={21} /></Card></TouchableOpacity>; }
const styles = StyleSheet.create({
  content: { padding: 20, paddingTop: 12, paddingBottom: 28 }, topRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 23 }, localChip: { backgroundColor: "#FFFFFF", paddingHorizontal: 10, paddingVertical: 7, borderRadius: 99, borderColor: "#DFF2E3", borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 5 }, localText: { fontSize: 11, fontWeight: "800", color: "#27733A" }, title: { color: palette.ink, fontSize: 30, lineHeight: 37, fontWeight: "900", letterSpacing: -1 }, subtitle: { color: palette.muted, fontSize: 14, marginTop: 5, marginBottom: 17 }, summary: { padding: 14, flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 17 }, summaryIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: palette.violetLight, justifyContent: "center", alignItems: "center" }, summaryText: { flex: 1 }, summaryTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, summaryDetail: { color: palette.muted, fontSize: 12, marginTop: 3 }, filters: { flexDirection: "row", gap: 7, marginBottom: 20, flexWrap: "wrap" }, filter: { height: 33, paddingHorizontal: 11, justifyContent: "center", borderRadius: 11, borderWidth: 1, borderColor: palette.line, backgroundColor: "#FFFFFF" }, filterActive: { backgroundColor: palette.violet, borderColor: palette.violet }, filterText: { color: palette.muted, fontWeight: "800", fontSize: 11 }, filterTextActive: { color: "#FFFFFF" }, listTitle: { color: palette.ink, fontSize: 18, fontWeight: "900", marginBottom: 10 }, row: { padding: 12, marginBottom: 9, flexDirection: "row", alignItems: "center", gap: 10 }, rowIcon: { width: 37, height: 37, borderRadius: 12, justifyContent: "center", alignItems: "center" }, rowCopy: { flex: 1 }, rowTitleLine: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 7 }, rowTitle: { color: palette.ink, fontSize: 13, fontWeight: "900", flex: 1 }, rowDetail: { color: palette.muted, fontSize: 11, marginTop: 4 }, rowMeta: { flexDirection: "row", alignItems: "center", gap: 6, color: palette.muted, marginTop: 6 }, dot: { height: 3, width: 3, borderRadius: 2, backgroundColor: "#BFC5D2" }, empty: { padding: 22, gap: 9, alignItems: "center" }, emptyText: { color: palette.muted, fontSize: 13 },
});
