import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppScreen, BrandMark, Card, Chevron, palette, PrivacyChip, SectionTitle, StatusPill } from "@/components/beepai-ui";
import { getPlan, useBeepAI } from "@/lib/beepai-context";

type ProfileItem = { icon: keyof typeof MaterialIcons.glyphMap; label: string; detail: string; action?: string };
export default function ProfileScreen() {
  const router = useRouter();
  const { currentPlanId } = useBeepAI();
  const plan = getPlan(currentPlanId);
  const items: ProfileItem[] = [{ icon: "shield", label: "Privacy & local data", detail: "Your work documents remain on this device." }, { icon: "cloud-off", label: "Offline execution", detail: "Most automations can run without the internet." }, { icon: "notifications-none", label: "Notifications", detail: "Control private completion alerts." }, { icon: "help-outline", label: "Support & help", detail: "Documentation, contact, and report an issue." }];
  return <AppScreen><FlatList data={items} keyExtractor={(item) => item.label} renderItem={({ item }) => <SettingsRow item={item} />} contentContainerStyle={styles.content} ListHeaderComponent={<>
    <View style={styles.topRow}><BrandMark /><PrivacyChip /></View><Text style={styles.title}>Profile</Text><Text style={styles.subtitle}>Personal settings and product controls.</Text>
    <Card style={styles.personCard}><View style={styles.avatar}><Text style={styles.avatarText}>J</Text></View><View style={styles.personCopy}><Text style={styles.personName}>Jean Uwimana</Text><Text style={styles.personPlan}>{plan.name} workspace</Text></View><View style={styles.editButton}><MaterialIcons name="verified-user" color={palette.violet} size={18} /></View></Card>
    <SectionTitle eyebrow="YOUR PLAN" title="Subscription" />
    <TouchableOpacity onPress={() => router.push("/plans" as never)} activeOpacity={0.76}><Card style={styles.planCard}><View style={[styles.planGlyph, { backgroundColor: `${plan.accent}16` }]}><MaterialIcons name="workspace-premium" size={21} color={plan.accent} /></View><View style={styles.planCopy}><View style={styles.planTitleLine}><Text style={styles.planName}>{plan.name}</Text><StatusPill label="Current plan" tone="violet" /></View><Text style={styles.planDetail}>{plan.price} / month · View plan details</Text></View><Chevron /></Card></TouchableOpacity>
    <SectionTitle eyebrow="SECURITY & PREFERENCES" title="Settings" />
  </>} ListFooterComponent={<View style={styles.footer}><View style={styles.footerMark}><Text style={styles.footerLetter}>B</Text></View><Text style={styles.footerTitle}>BeepAI</Text><Text style={styles.footerText}>Your work. Automated. Privately.</Text><Text style={styles.version}>Version 1.0.0</Text></View>} /></AppScreen>;
}
function SettingsRow({ item }: { item: ProfileItem }) { return <Card style={styles.setting}><View style={styles.settingIcon}><MaterialIcons name={item.icon} color={palette.violet} size={20} /></View><View style={styles.settingCopy}><Text style={styles.settingLabel}>{item.label}</Text><Text style={styles.settingDetail}>{item.detail}</Text></View><Chevron /></Card>; }
const styles = StyleSheet.create({
  content: { padding: 20, paddingTop: 12, paddingBottom: 28 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 23 }, title: { color: palette.ink, fontSize: 30, lineHeight: 37, fontWeight: "900", letterSpacing: -1 }, subtitle: { color: palette.muted, fontSize: 14, marginTop: 5, marginBottom: 17 }, personCard: { padding: 14, flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 28 }, avatar: { height: 46, width: 46, borderRadius: 16, backgroundColor: palette.violet, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontWeight: "900", fontSize: 18 }, personCopy: { flex: 1 }, personName: { color: palette.ink, fontWeight: "900", fontSize: 15 }, personPlan: { color: palette.muted, fontSize: 12, marginTop: 3 }, editButton: { height: 35, width: 35, borderRadius: 12, backgroundColor: palette.violetLight, alignItems: "center", justifyContent: "center" }, planCard: { padding: 13, flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 27 }, planGlyph: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, planCopy: { flex: 1 }, planTitleLine: { flexDirection: "row", gap: 7, alignItems: "center" }, planName: { color: palette.ink, fontSize: 15, fontWeight: "900" }, planDetail: { color: palette.muted, fontSize: 11, marginTop: 4 }, setting: { padding: 12, flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 9 }, settingIcon: { height: 38, width: 38, borderRadius: 12, backgroundColor: palette.violetLight, alignItems: "center", justifyContent: "center" }, settingCopy: { flex: 1 }, settingLabel: { color: palette.ink, fontSize: 13, fontWeight: "900" }, settingDetail: { color: palette.muted, fontSize: 11, marginTop: 3, lineHeight: 15 }, footer: { alignItems: "center", paddingTop: 27, paddingBottom: 6 }, footerMark: { height: 30, width: 30, borderRadius: 10, backgroundColor: palette.violet, alignItems: "center", justifyContent: "center" }, footerLetter: { color: "#fff", fontWeight: "900", fontSize: 18 }, footerTitle: { color: palette.ink, fontSize: 15, fontWeight: "900", marginTop: 8 }, footerText: { color: palette.muted, fontSize: 12, marginTop: 3 }, version: { color: "#98A2B3", fontSize: 11, marginTop: 10 },
});
