import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams } from "expo-router";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { AppScreen, Card, PageHeader, palette, StatusPill } from "@/components/beepai-ui";
import { useBeepAI } from "@/lib/beepai-context";
import type { WorkflowStep } from "@/lib/beepai-data";

export default function WorkflowScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { automations } = useBeepAI(); const automation = automations.find((item) => item.id === id);
  if (!automation) return <AppScreen><PageHeader title="Workflow" back /></AppScreen>;
  return <AppScreen><FlatList data={automation.steps} keyExtractor={(item) => item.id} renderItem={({ item, index }) => <WorkflowStepRow item={item} index={index} last={index === automation.steps.length - 1} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<><PageHeader title="Workflow" subtitle="A private, local execution plan" back /><Card style={styles.summary}><View style={styles.summaryGlyph}><MaterialIcons name="account-tree" color={palette.primary} size={22} /></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>{automation.name}</Text><Text style={styles.summaryText}>{automation.steps.length} steps · {automation.schedule}</Text></View><StatusPill label="Verified" tone="green" /></Card><Text style={styles.flowLabel}>EXECUTION FLOW</Text></>} ListFooterComponent={<Card style={styles.note}><MaterialIcons name="info-outline" color={palette.blue} size={19} /><Text style={styles.noteText}>This workflow is data-driven. Future action types can be added without changing the automation screen.</Text></Card>} /></AppScreen>;
}
function WorkflowStepRow({ item, index, last }: { item: WorkflowStep; index: number; last: boolean }) { const tones = { trigger: [palette.primaryLight, palette.primary], input: ["#EAF1FF", palette.blue], process: ["#FFF4E6", palette.amber], output: ["#EAF9EE", palette.mint], notify: [palette.primaryLight, palette.primary] } as const; const [backgroundColor, color] = tones[item.kind]; return <View style={styles.stepWrap}><View style={styles.track}><View style={[styles.index, { backgroundColor, borderColor: color }]}><Text style={[styles.indexText, { color }]}>{index + 1}</Text></View>{!last && <View style={styles.line} />}</View><Card style={styles.stepCard}><View style={[styles.stepGlyph, { backgroundColor }]}><MaterialIcons name={item.icon} color={color} size={20} /></View><View style={styles.stepCopy}><Text style={styles.stepTitle}>{item.label}</Text><Text style={styles.stepDetail}>{item.detail}</Text><Text style={[styles.stepKind, { color }]}>{item.kind.toUpperCase()}</Text></View></Card></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingTop: 9, paddingBottom: 27 }, summary: { padding: 14, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 5, marginBottom: 25 }, summaryGlyph: { height: 41, width: 41, borderRadius: 13, backgroundColor: palette.primaryLight, justifyContent: "center", alignItems: "center" }, summaryCopy: { flex: 1 }, summaryTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, summaryText: { color: palette.muted, fontSize: 11, marginTop: 3 }, flowLabel: { color: palette.primary, fontSize: 11, letterSpacing: 0.9, fontWeight: "900", marginBottom: 11 }, stepWrap: { flexDirection: "row", minHeight: 103 }, track: { width: 42, alignItems: "center" }, index: { height: 29, width: 29, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center", zIndex: 1 }, indexText: { fontSize: 12, fontWeight: "900" }, line: { position: "absolute", top: 29, bottom: -2, width: 2, backgroundColor: "#DDD7F4" }, stepCard: { padding: 12, flex: 1, flexDirection: "row", gap: 10, alignSelf: "flex-start" }, stepGlyph: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" }, stepCopy: { flex: 1 }, stepTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, stepDetail: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, stepKind: { fontSize: 10, fontWeight: "900", letterSpacing: 0.6, marginTop: 7 }, note: { backgroundColor: "#F5F8FF", borderColor: "#D6E4FF", padding: 13, flexDirection: "row", gap: 9, marginTop: 6 }, noteText: { flex: 1, color: "#4A6191", fontSize: 11, lineHeight: 16 },
});
